package appreciation;
// default package



/**
 * Abstractappreciation generated by MyEclipse Persistence Tools
 */

public abstract class Abstractappreciation  implements java.io.Serializable {


    // Fields    

     private Integer ordernum;
     private Integer score;
     private String appreciation;


    // Constructors

    /** default constructor */
    public Abstractappreciation() {
    }

	/** minimal constructor */
    public Abstractappreciation(Integer ordernum) {
        this.ordernum = ordernum;
    }
    
    /** full constructor */
    public Abstractappreciation(Integer ordernum, Integer score, String appreciation) {
        this.ordernum = ordernum;
        this.score = score;
        this.appreciation = appreciation;
    }

   
    // Property accessors

    public Integer getOrdernum() {
        return this.ordernum;
    }
    
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }

    public String getAppreciation() {
        return this.appreciation;
    }
    
    public void setAppreciation(String appreciation) {
        this.appreciation = appreciation;
    }
   








}