package fudao;
// default package



/**
 * Abstractfudao generated by MyEclipse Persistence Tools
 */

public abstract class Abstractfudao  implements java.io.Serializable {


    // Fields    

     private Integer pro;
     private String name;
     private String address;
     private String phone;
     private String starttime;


    // Constructors

    /** default constructor */
    public Abstractfudao() {
    }

	/** minimal constructor */
    public Abstractfudao(String name, String address, String phone) {
        this.name = name;
        this.address = address;
        this.phone = phone;
    }
    
    /** full constructor */
    public Abstractfudao(int pro,String name, String address, String phone, String starttime) {
        this.pro=pro;
    	this.name = name;
        this.address = address;
        this.phone = phone;
        this.starttime = starttime;
    }

   
    // Property accessors

    public Integer getPro() {
        return this.pro;
    }
    
    public void setPro(Integer pro) {
        this.pro = pro;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }
   








}