package adminuser;
// default package



/**
 * Abstractadminuser generated by MyEclipse Persistence Tools
 */

public abstract class Abstractadminuser  implements java.io.Serializable {


    // Fields    

     private String username;
     private String password;
     private String cellphone;
     private String granted;
     private String email;
     private String sex;
     private String region;


    // Constructors

    /** default constructor */
    public Abstractadminuser() {
    }

	/** minimal constructor */
    public Abstractadminuser(String username, String password, String cellphone) {
        this.username = username;
        this.password = password;
        this.cellphone = cellphone;
    }
    
    /** full constructor */
    public Abstractadminuser(String username, String password, String cellphone, String granted, String email, String sex, String region) {
        this.username = username;
        this.password = password;
        this.cellphone= cellphone;
        this.granted = granted;
        this.email = email;
        this.sex = sex;
        this.region = region;
    }

   
    // Property accessors

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getCellphone() {
        return this.cellphone;
    }
    
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    public String getGranted() {
        return this.granted;
    }
    
    public void setGranted(String granted) {
        this.granted = granted;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
   








}