package text;
// default package



/**
 * Abstracttext generated by MyEclipse Persistence Tools
 */

public abstract class Abstracttext  implements java.io.Serializable {


    // Fields    

     private String name;
     private String url;
     private String class_;


    // Constructors

    /** default constructor */
    public Abstracttext() {
    }

    
    /** full constructor */
    public Abstracttext(String name, String url, String class_) {
        this.name = name;
        this.url = url;
        this.class_ = class_;
    }

   
    // Property accessors

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
   








}