package text;
// default package
// Generated by MyEclipse Persistence Tools



/**
 * text generated by MyEclipse Persistence Tools
 */
public class text extends Abstracttext implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public text() {
    }

    
    /** full constructor */
    public text(String name, String url, String class_) {
        super(name, url, class_);        
    }
   
}
