package myorder;
// default package



/**
 * Abstractmyorder generated by MyEclipse Persistence Tools
 */

public abstract class Abstractmyorder  implements java.io.Serializable {


    // Fields    

     private Integer ordernum;
     private String teacher;
     private String student;
     private String cellphone;
     private String homephone;
     private String datetime;
     private String status;
     private String region;
     private String teachtime;
     private String pay;
     private Integer fee;
     private Integer days;


    // Constructors

    /** default constructor */
    public Abstractmyorder() {
    }

	/** minimal constructor */
    public Abstractmyorder(Integer ordernum, String teacher, String student, String cellphone, String datetime, String status, String region, String teachtime, String pay,Integer fee,Integer days) {
        this.ordernum = ordernum;
        this.teacher = teacher;
        this.student = student;
        this.cellphone = cellphone;
        this.datetime = datetime;
        this.status = status;
        this.region = region;
        this.teachtime = teachtime;
        this.pay = pay;
        this.fee=fee;
        this.days=days;
    }
    
    /** full constructor */
    public Abstractmyorder(Integer ordernum, String teacher, String student, String cellphone, String homephone, String datetime, String status, String region, String teachtime, String pay,Integer fee,Integer days) {
        this.ordernum = ordernum;
        this.teacher = teacher;
        this.student = student;
        this.cellphone = cellphone;
        this.homephone = homephone;
        this.datetime = datetime;
        this.status = status;
        this.region = region;
        this.teachtime = teachtime;
        this.pay = pay;
        this.fee=fee;
        this.days=days;
    }

   
    // Property accessors

    public Integer getOrdernum() {
        return this.ordernum;
    }
    
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    public String getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public String getStudent() {
        return this.student;
    }
    
    public void setStudent(String student) {
        this.student = student;
    }

    public String getCellphone() {
        return this.cellphone;
    }
    
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    public String getHomephone() {
        return this.homephone;
    }
    
    public void setHomephone(String homephone) {
        this.homephone = homephone;
    }

    public String getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }

    public String getTeachtime() {
        return this.teachtime;
    }
    
    public void setTeachtime(String teachtime) {
        this.teachtime = teachtime;
    }

    public String getPay() {
        return this.pay;
    }
    
    public void setPay(String pay) {
        this.pay = pay;
    }
    public Integer getFee() {
        return this.fee;
    }
    public void setFee(Integer fee) {
        this.fee = fee;
    }
    public Integer getDays() {
        return this.days;
    }
    public void setDays(Integer days) {
        this.days = days;
    }







}