package myorder;
// default package
// Generated by MyEclipse Persistence Tools



/**
 * myorder generated by MyEclipse Persistence Tools
 */
public class myorder extends Abstractmyorder implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public myorder() {
    }

	/** minimal constructor */
    public myorder(Integer ordernum, String teacher, String student, String cellphone, String datetime, String status, String region, String teachtime, String pay,Integer fee,Integer days) {
        super(ordernum, teacher, student, cellphone, datetime, status, region, teachtime, pay,fee,days);        
    }
    
    /** full constructor */
    public myorder(Integer ordernum, String teacher, String student, String cellphone, String homephone, String datetime, String status, String region, String teachtime, String pay,Integer fee,Integer days) {
        super(ordernum, teacher, student, cellphone, homephone, datetime, status, region, teachtime, pay,fee,days);        
    }
   
}
