package upload;
// default package
// Generated by MyEclipse Persistence Tools



/**
 * upload generated by MyEclipse Persistence Tools
 */
public class upload extends Abstractupload implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public upload() {
    }

	/** minimal constructor */
    public upload(String name) {
        super(name);        
    }
    
    /** full constructor */
    public upload(String name, String detail) {
        super(name, detail);        
    }
   
}
