package userinf0;
// default package



/**
 * Abstractuserinf0 generated by MyEclipse Persistence Tools
 */

public abstract class Abstractuserinf0  implements java.io.Serializable {


    // Fields    

     private String username;

     private String password;
     private String idcard;
     private String cellphone;
     private String homephone;
     private String qqnum;
     private String msnnum;
     private String email;


    // Constructors

    /** default constructor */
    public Abstractuserinf0() {
    }

	/** minimal constructor */
    public Abstractuserinf0(String username, String password, String idcard, String cellphone, String homephone) {
        this.username = username;

        this.password = password;
        this.idcard = idcard;
        this.cellphone = cellphone;
        this.homephone = homephone;
    }
    
    /** full constructor */
    public Abstractuserinf0(String username, String password, String idcard, String cellphone, String homephone, String qqnum, String msnnum, String email) {
        this.username = username;

        this.password = password;
        this.idcard = idcard;
        this.cellphone = cellphone;
        this.homephone = homephone;
        this.qqnum = qqnum;
        this.msnnum = msnnum;
        this.email = email;
    }

   
    // Property accessors

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

 

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getIdcard() {
        return this.idcard;
    }
    
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getCellphone() {
        return this.cellphone;
    }
    
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    public String getHomephone() {
        return this.homephone;
    }
    
    public void setHomephone(String homephone) {
        this.homephone = homephone;
    }

    public String getQqnum() {
        return this.qqnum;
    }
    
    public void setQqnum(String qqnum) {
        this.qqnum = qqnum;
    }

    public String getMsnnum() {
        return this.msnnum;
    }
    
    public void setMsnnum(String msnnum) {
        this.msnnum = msnnum;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
   








}