package userinf0;
// default package
// Generated by MyEclipse Persistence Tools



/**
 * userinf0 generated by MyEclipse Persistence Tools
 */
public class userinf0 extends Abstractuserinf0 implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public userinf0() {
    }

	/** minimal constructor */
    public userinf0(String username,String password, String idcard, String cellphone, String homephone) {
        super(username, password, idcard, cellphone, homephone);        
    }
    
    /** full constructor */
    public userinf0(String username, String password, String idcard, String cellphone, String homephone, String qqnum, String msnnum, String email) {
        super(username, password, idcard, cellphone, homephone, qqnum, msnnum, email);        
    }
   
}
