package userinf1;
// default package



/**
 * Abstractuserinf1 generated by MyEclipse Persistence Tools
 */

public abstract class Abstractuserinf1  implements java.io.Serializable {


    // Fields    

     private String username;
     private String classgrade;
     private String subject;
     private String region;
     private String sex;
     private String video;
     private Integer score;


    // Constructors

    /** default constructor */
    public Abstractuserinf1() {
    }

	/** minimal constructor */
    public Abstractuserinf1(String username, String classgrade, String subject, String region, String video, Integer score) {
        this.username = username;
        this.classgrade = classgrade;
        this.subject = subject;
        this.region = region;
        this.video = video;
        this.score = score;
    }
    
    /** full constructor */
    public Abstractuserinf1(String username, String classgrade, String subject, String region, String sex, String video, Integer score) {
        this.username = username;
        this.classgrade = classgrade;
        this.subject = subject;
        this.region = region;
        this.sex = sex;
        this.video = video;
        this.score = score;
    }

   
    // Property accessors

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getClassgrade() {
        return this.classgrade;
    }
    
    public void setClassgrade(String classgrade) {
        this.classgrade = classgrade;
    }

    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }

    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }
   








}