package userinf1;
// default package
// Generated by MyEclipse Persistence Tools



/**
 * userinf1 generated by MyEclipse Persistence Tools
 */
public class userinf1 extends Abstractuserinf1 implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public userinf1() {
    }

	/** minimal constructor */
    public userinf1(String username, String classgrade, String subject, String region, String video, Integer score) {
        super(username, classgrade, subject, region, video, score);        
    }
    
    /** full constructor */
    public userinf1(String username, String classgrade, String subject, String region, String sex, String video, Integer score) {
        super(username, classgrade, subject, region, sex, video, score);        
    }
   
}
