package wang;

// Generated by MyEclipse Persistence Tools

/**
 * Admin generated by MyEclipse Persistence Tools
 */
public class Admin extends AbstractAdmin implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Admin() {
	}

	/** minimal constructor */
	public Admin(String adminuser) {
		super(adminuser);
	}

	/** full constructor */
	public Admin(String adminuser, String adminpass) {
		super(adminuser, adminpass);
	}

}
